### ISSUE TITLE
Hyväksytäänkö .NET-refaktorointia?

### ISSUE THREAD

**Issue by veikkoeeva** [aste-hsc/ASTE-Prototype#2]
Hei!

Katsoin .NET-koodia ja ajattelin kysyä, otatteko vastaan refaktorointiehdotuksia? Miten laajoja (näin alussa erityisesti)?

**Comment by ToniIltanen** [comment]
Toki otetaan vastaan! Itse protokokonaisuus ei ole vielä kovinkaan optimoitu, lähtökohtaisesti protossa ainoat "tärkeät" komponentit ovat API Discovery ja Public Rest, ja niiden tuomat vaatimukset moduuleille, prosesseille ja web applikaatioille. Muut projektit on ainoastaan demoa varten tehty, esimerkkimoduuleiksi ja prosesseiksi.

**Comment by veikkoeeva** [comment]
Vielä lisäkymys, onko näitä siis oikeastaan tarkoitus ajaa tuotannossa vai vain hakea rajapintoja? Mitä suotta refaktoroimaan, jos on poisheittokoodia, nimittäin. :)

**Comment by ToniIltanen** [comment]
Hyvä kysymys! Tätä ei meinaan ole tarkoitus ajaa tuotannossa, vaan proto toimii pohjana/visiona tulevalle alustalle. Eli ratkaiseva asia on itse API Discovery, jonka kautta prosessit ja moduulit näkevät toisensa, sekä public rest, jonka kautta kutsu ohjautuu api discoveryn kautta julkiselle prosessille.

Tästä varmaan pitäisi oma dokkari kirjoittaa, eli mitä tässä protossa taustalla ylipäätään tapahtuu. 
Lähtökohtaisesti toiminta on seuraavanlainen: web applikaatio kutsuu julkista rajapintaa (public rest api), joka ohjaa kutsun halutulle prosessille. Prosessi taasen kutsuu moduuleita (mikropalveluita) businesslogiikkansa mukaisesti, ja lopulta prosessi palauttaa tiedot public rest apiin, joka taasen ohjaa ne takaisin kutsuvaan päähän. API Discovery toimii väylänä prosesseihin ja moduuleihin, palauttaen tiedon siitä missä yksittäinen moduuli/prosessi sijaitsee, ja tarkistaa tarvittavat api avaimet ja kutsut.

Mitä tulee koodiin, Public Rest ja Api Discovery projekteja kannattaa katselmoida myös refaktorointimielessä!

**Comment by veikkoeeva** [comment]
@ToniIltanen Kiits. Taidan jättää väliin sitten. Bongasin nimittäin, että projektia voisi "näppäröittää"  tyyliin "git clone -> käynnistä VS -> paina F5" ja olisi www-rajapinta ja API:t ajossa.

En tullut oikeastaan änkyröimään, mutta huomiona, että parempi .gitignore on muuten saatavissa [täältä](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore). Jos oletetaan VS, myös tietokannan voi generoida ja laittaa ajoon samalla kerralla (LocalDb, SSDT, DacPack jne.). Nuget-paketteja, binäärejä, ja joitain VS:n tiedostoja ei myöskään tarvitse laittaa Gitiin ja ehkä myöhemmin muutakin, kun/jos projekti alkaa. :)

**Comment by ToniIltanen** [comment]
:+1:

**Comment by ToniIltanen** [comment]
Tällä siis en tarkoittanut etteikö protoa voitaisi optimoida. Protoa tullaan laajentamaan kehityksen edetessä. Varsinainen virallinen julkaisu tulee ASTE konsortion toimesta aikanaan, josta virallinen development haara tullaan eriyttämään. Siihen asti kehityksessä tullaan protoa käyttämään, joten kaikki optimointiehdotukset otetaan mieluusti vastaan (kuten kaikki muutkin laajennos ja kehitysideat!)

**Comment by jaakkokorhonen** [comment]
Joo tästä siirtyy varsinaiseen versioon ne osat mitä todetaan hyviksi jutuiksi, vaikka onkin rakennettu muuttumaan.

Jos on mieluisa builderi tiedossa, saa ehdottaa. Tässä nyt ihan tarkoituksella ei tehty ihan kaikkea ensimmäiseen julkaisuun.

**Comment by veikkoeeva** [comment]
Aika on kovasti kortilla, vaikka tämän toki tärkeäksi näen. Muuten, @ToniIltanen ja @jaakkokorhonen, GitHub lähettää viestin, jos viittaatte nimimerkillä. On helpompaa pysyä perässä, kun keskusteluita saattaa olla useita. :)
